//Sabrina Mato(222071) y Pamela Quesada(171498)
package Interfaz;

import obligatorio2_syp.Obligatorio2_SyP;
import Dominio.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class MenuPpal extends javax.swing.JFrame {

    private Sistema sistema;

    /**
     * Creates new form MenuPpal
     */
    public MenuPpal() {
        initComponents();
    }

    public MenuPpal(Sistema sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menReg = new javax.swing.JMenu();
        itmRegModRubro = new javax.swing.JMenuItem();
        itmRegCapataz = new javax.swing.JMenuItem();
        itmRegPropietario = new javax.swing.JMenuItem();
        itmRegObra = new javax.swing.JMenuItem();
        menGas = new javax.swing.JMenu();
        itmRegistroGastoObra = new javax.swing.JMenuItem();
        itmPagoGasto = new javax.swing.JMenuItem();
        itmEstadoObra = new javax.swing.JMenuItem();
        menImpExp = new javax.swing.JMenu();
        itmImportacionDatosObraNueva = new javax.swing.JMenuItem();
        itmExportacionPropietariosCapataces = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Pequeñas Obras - Realizado por Pamela Quesada y Sabrina Mato ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        menReg.setMnemonic('f');
        menReg.setText("Registros");

        itmRegModRubro.setMnemonic('o');
        itmRegModRubro.setText("Registrar/Modificar Rubro");
        itmRegModRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegModRubroActionPerformed(evt);
            }
        });
        menReg.add(itmRegModRubro);

        itmRegCapataz.setMnemonic('s');
        itmRegCapataz.setText("Registrar Capataz");
        itmRegCapataz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegCapatazActionPerformed(evt);
            }
        });
        menReg.add(itmRegCapataz);

        itmRegPropietario.setMnemonic('a');
        itmRegPropietario.setText("Registro de Propietario");
        itmRegPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegPropietarioActionPerformed(evt);
            }
        });
        menReg.add(itmRegPropietario);

        itmRegObra.setMnemonic('x');
        itmRegObra.setText("Registro de Obra");
        itmRegObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegObraActionPerformed(evt);
            }
        });
        menReg.add(itmRegObra);

        menuBar.add(menReg);

        menGas.setMnemonic('e');
        menGas.setText("Gastos");

        itmRegistroGastoObra.setMnemonic('t');
        itmRegistroGastoObra.setText("Registro de gasto para obra");
        itmRegistroGastoObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegistroGastoObraActionPerformed(evt);
            }
        });
        menGas.add(itmRegistroGastoObra);

        itmPagoGasto.setMnemonic('y');
        itmPagoGasto.setText("Pago de gasto");
        itmPagoGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmPagoGastoActionPerformed(evt);
            }
        });
        menGas.add(itmPagoGasto);

        itmEstadoObra.setMnemonic('p');
        itmEstadoObra.setText("Estado de obra");
        itmEstadoObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEstadoObraActionPerformed(evt);
            }
        });
        menGas.add(itmEstadoObra);

        menuBar.add(menGas);

        menImpExp.setMnemonic('h');
        menImpExp.setText("Importación y Exportación");

        itmImportacionDatosObraNueva.setMnemonic('c');
        itmImportacionDatosObraNueva.setText("Importación de datos para obra nueva");
        itmImportacionDatosObraNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmImportacionDatosObraNuevaActionPerformed(evt);
            }
        });
        menImpExp.add(itmImportacionDatosObraNueva);

        itmExportacionPropietariosCapataces.setMnemonic('a');
        itmExportacionPropietariosCapataces.setText("Exportación de datos de Propietarios y Capataces");
        itmExportacionPropietariosCapataces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExportacionPropietariosCapatacesActionPerformed(evt);
            }
        });
        menImpExp.add(itmExportacionPropietariosCapataces);

        menuBar.add(menImpExp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(614, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmRegObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegObraActionPerformed
        RegistroObra ventanaObra = new RegistroObra(sistema);
        ventanaObra.setVisible(true);
    }//GEN-LAST:event_itmRegObraActionPerformed

    private void itmRegModRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegModRubroActionPerformed
        // TODO add your handling code here:
        RegistroModificarRubro ventanaRubro = new RegistroModificarRubro(sistema);
        ventanaRubro.setVisible(true);
    }//GEN-LAST:event_itmRegModRubroActionPerformed

    private void itmRegCapatazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegCapatazActionPerformed
        // TODO add your handling code here:
        RegistrarCapataz ventanaCapataz = new RegistrarCapataz(sistema);
        ventanaCapataz.setVisible(true);

    }//GEN-LAST:event_itmRegCapatazActionPerformed

    private void itmRegPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegPropietarioActionPerformed
        // TODO add your handling code here:
        RegistrarPropietario ventanaPropietario = new RegistrarPropietario(sistema);
        ventanaPropietario.setVisible(true);
    }//GEN-LAST:event_itmRegPropietarioActionPerformed

    private void itmRegistroGastoObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegistroGastoObraActionPerformed
        // TODO add your handling code here:
        //Gasto gasto = new Gasto();
        RegistroGastoObra ventanaGastoObra = new RegistroGastoObra(sistema);
        ventanaGastoObra.setVisible(true);
    }//GEN-LAST:event_itmRegistroGastoObraActionPerformed

    private void itmPagoGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmPagoGastoActionPerformed
        // TODO add your handling code here:
        PagoGasto ventanaPagoGasto = new PagoGasto(sistema);
        ventanaPagoGasto.setVisible(true);
    }//GEN-LAST:event_itmPagoGastoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            // TODO add your handling code here:
            Obligatorio2_SyP.guardarSistema(sistema);
            System.out.println("Se guardo sistema");
        } catch (IOException ex) {
            Logger.getLogger(MenuPpal.class.getName()).log(Level.SEVERE, null, ex);
        }    }//GEN-LAST:event_formWindowClosing

    private void itmEstadoObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEstadoObraActionPerformed
        // TODO add your handling code here:
        EstadoObra ventanaEstadoObra = new EstadoObra(sistema);
        ventanaEstadoObra.setVisible(true);
    }//GEN-LAST:event_itmEstadoObraActionPerformed

    private void itmExportacionPropietariosCapatacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExportacionPropietariosCapatacesActionPerformed
        // TODO add your handling code here:
        String[] opciones = {"Ordenar por Nombre", "Ordenar por Cédula"};
        int eleccion = JOptionPane.showOptionDialog(null, "¿Cómo deseas ordenarlos?", "Ordenar", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        if (eleccion == 0) {
            Obligatorio2_SyP.exportarDatos(0, sistema);
        } else if (eleccion == 1) {
            Obligatorio2_SyP.exportarDatos(1, sistema);
        }
    }//GEN-LAST:event_itmExportacionPropietariosCapatacesActionPerformed

    private void itmImportacionDatosObraNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmImportacionDatosObraNuevaActionPerformed
        // TODO add your handling code here:
        String nombreArch = JOptionPane.showInputDialog(null, "Ingrese nombre del archivo a importar", "Importar Archivo", JOptionPane.QUESTION_MESSAGE);
        Obligatorio2_SyP.importarObra(nombreArch, sistema);

    }//GEN-LAST:event_itmImportacionDatosObraNuevaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmEstadoObra;
    private javax.swing.JMenuItem itmExportacionPropietariosCapataces;
    private javax.swing.JMenuItem itmImportacionDatosObraNueva;
    private javax.swing.JMenuItem itmPagoGasto;
    private javax.swing.JMenuItem itmRegCapataz;
    private javax.swing.JMenuItem itmRegModRubro;
    private javax.swing.JMenuItem itmRegObra;
    private javax.swing.JMenuItem itmRegPropietario;
    private javax.swing.JMenuItem itmRegistroGastoObra;
    private javax.swing.JMenu menGas;
    private javax.swing.JMenu menImpExp;
    private javax.swing.JMenu menReg;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
