//Sabrina Mato(222071) y Pamela Quesada(171498)

package Interfaz;

import Dominio.*;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;

public class PagoGasto extends javax.swing.JFrame
        implements Observer {

    private Sistema sistema;

    /**
     * Creates new form PagoGasto
     */
    public PagoGasto() {
        initComponents();
    }

    public void update(Observable o, Object ob) {
        lstObrasPagoGasto.setListData(sistema.arrayObras());
    }

    public PagoGasto(Sistema sistema) {
        initComponents();
        this.sistema = sistema;
        sistema.addObserver(this);
        objetoAPantalla();

    }

    private void objetoAPantalla() {
        lstObrasPagoGasto.setListData(sistema.arrayObras());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPagoGasto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstObrasPagoGasto = new javax.swing.JList<>();
        lblObra = new javax.swing.JLabel();
        lblGastosImpagos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstGastosImpagos = new javax.swing.JList<>(new DefaultListModel<>());
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstGastosReintegrados = new javax.swing.JList<>();
        lblGastosReintegrados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pago de gasto");

        pnlPagoGasto.setLayout(null);

        lstObrasPagoGasto.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstObrasPagoGasto.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstObrasPagoGastoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstObrasPagoGasto);

        pnlPagoGasto.add(jScrollPane1);
        jScrollPane1.setBounds(40, 110, 150, 200);

        lblObra.setText("Obras:");
        pnlPagoGasto.add(lblObra);
        lblObra.setBounds(40, 90, 50, 20);

        lblGastosImpagos.setText("Gastos impagos:");
        pnlPagoGasto.add(lblGastosImpagos);
        lblGastosImpagos.setBounds(230, 90, 110, 20);

        jScrollPane2.setViewportView(lstGastosImpagos);

        lstGastosImpagos.setToolTipText("");
        lstGastosImpagos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lstGastosImpagosPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(lstGastosImpagos);

        pnlPagoGasto.add(jScrollPane2);
        jScrollPane2.setBounds(230, 110, 200, 200);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Reintegro de Gastos");
        pnlPagoGasto.add(jLabel2);
        jLabel2.setBounds(200, 30, 200, 40);

        jButton1.setText("Reintegrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlPagoGasto.add(jButton1);
        jButton1.setBounds(450, 180, 110, 40);

        lstGastosReintegrados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(lstGastosReintegrados);

        pnlPagoGasto.add(jScrollPane3);
        jScrollPane3.setBounds(180, 360, 250, 60);

        lblGastosReintegrados.setText("Gastos reintegrados:");
        pnlPagoGasto.add(lblGastosReintegrados);
        lblGastosReintegrados.setBounds(180, 340, 140, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPagoGasto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPagoGasto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(614, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        List<String> gastosAReintegrar = lstGastosImpagos.getSelectedValuesList();
        System.out.println(gastosAReintegrar);
        lstGastosReintegrados.setModel(new DefaultListModel<>());
        DefaultListModel<String> model = (DefaultListModel<String>) lstGastosReintegrados.getModel();
        for (String g : gastosAReintegrar) {
            int numGasto = Integer.parseInt(g.substring(0, g.indexOf(".")));
            model.addElement(g);
            System.out.println("Gasto a reintegrar: " + sistema.darGasto(numGasto));
            //sistema.darGasto(numGasto).reintegrarGasto();
            sistema.reintegrarGasto(sistema.darGasto(numGasto));
        }
        System.out.println(sistema.getListaGastos());
        lstObrasPagoGasto.clearSelection();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lstObrasPagoGastoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstObrasPagoGastoValueChanged
        // TODO add your handling code here:
        String numObraAux = lstObrasPagoGasto.getSelectedValue();
        if (numObraAux != null) {
            String sNumObra = "";
            for (int i = 0; i < numObraAux.indexOf("-"); i++) {
                sNumObra += numObraAux.charAt(i);
            }
            int numObra = Integer.parseInt(sNumObra);
            String[] arrayImpagos = new String[sistema.gastosImpagosObra(numObra).size()];
            for (int i = 0; i < arrayImpagos.length; i++) {
                Gasto g = sistema.gastosImpagosObra(numObra).get(i);
                String gastoInfo = g.getNumero() + ". " + g.getDescripcion() + " $" + g.getMonto();
                arrayImpagos[i] = gastoInfo;
            }
            lstGastosImpagos.setListData(arrayImpagos);
        } else {
            lstGastosImpagos.setListData(new String[0]);
        }

    }//GEN-LAST:event_lstObrasPagoGastoValueChanged

    private void lstGastosImpagosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lstGastosImpagosPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lstGastosImpagosPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagoGasto().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblGastosImpagos;
    private javax.swing.JLabel lblGastosReintegrados;
    private javax.swing.JLabel lblObra;
    private javax.swing.JList<String> lstGastosImpagos;
    private javax.swing.JList<String> lstGastosReintegrados;
    private javax.swing.JList<String> lstObrasPagoGasto;
    private javax.swing.JPanel pnlPagoGasto;
    // End of variables declaration//GEN-END:variables

}
