//Sabrina Mato(222071) y Pamela Quesada(171498)
package Interfaz;

import Dominio.*;
import Dominio.Sistema;
import javax.swing.JOptionPane;

public class RegistrarCapataz extends javax.swing.JFrame {

    private Sistema sistema;

    /**
     * Creates new form RegistrarCaparaz
     */
    public RegistrarCapataz() {
        initComponents();
    }

    public RegistrarCapataz(Sistema sistema) {
        this.sistema = sistema;
        initComponents();
        objetoAPantalla();
    }
    
        private void objetoAPantalla() {
            
        txtNombreCapataz.setText("");
        txtCedulaCapataz.setText("");
        txtDireccionCapataz.setText("");
        txtAnioCapataz.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreCapataz = new javax.swing.JLabel();
        txtNombreCapataz = new javax.swing.JTextField();
        txtCedulaCapataz = new javax.swing.JTextField();
        lblCedulaCapataz = new javax.swing.JLabel();
        txtDireccionCapataz = new javax.swing.JTextField();
        lblDireccionCapataz = new javax.swing.JLabel();
        txtAnioCapataz = new javax.swing.JTextField();
        lblAnioCapataz = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarCapataz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Capataz");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lblNombreCapataz.setText("Nombre:");
        jPanel1.add(lblNombreCapataz);
        lblNombreCapataz.setBounds(170, 140, 90, 16);
        jPanel1.add(txtNombreCapataz);
        txtNombreCapataz.setBounds(270, 132, 168, 30);
        jPanel1.add(txtCedulaCapataz);
        txtCedulaCapataz.setBounds(270, 172, 168, 30);

        lblCedulaCapataz.setText("Cédula:");
        jPanel1.add(lblCedulaCapataz);
        lblCedulaCapataz.setBounds(170, 180, 93, 16);

        txtDireccionCapataz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionCapatazActionPerformed(evt);
            }
        });
        jPanel1.add(txtDireccionCapataz);
        txtDireccionCapataz.setBounds(270, 212, 168, 30);

        lblDireccionCapataz.setText("Dirección:");
        jPanel1.add(lblDireccionCapataz);
        lblDireccionCapataz.setBounds(170, 220, 93, 16);

        txtAnioCapataz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioCapatazActionPerformed(evt);
            }
        });
        jPanel1.add(txtAnioCapataz);
        txtAnioCapataz.setBounds(270, 252, 168, 30);

        lblAnioCapataz.setText("Año de ingreso:");
        jPanel1.add(lblAnioCapataz);
        lblAnioCapataz.setBounds(170, 260, 265, 16);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Registro Capataz:");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 25));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(220, 60, 130, 28);

        btnRegistrarCapataz.setText("Registrar");
        btnRegistrarCapataz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCapatazActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarCapataz);
        btnRegistrarCapataz.setBounds(240, 340, 99, 34);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 580, 480);

        setSize(new java.awt.Dimension(614, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarCapatazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCapatazActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombreCapataz.getText();
        String cedula = txtCedulaCapataz.getText();
        String direccion = txtDireccionCapataz.getText();
        int anio = 0;

        if (datosValidos(nombre, cedula, direccion, anio) == 1) {
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            if (datosValidos(nombre, cedula, direccion, anio) == 2) {
                JOptionPane.showMessageDialog(null, "El año es invalido", "Error", JOptionPane.WARNING_MESSAGE);
            } else {
                if (sistema.existeCapataz(cedula)) {
                    JOptionPane.showMessageDialog(this, "El capataz ya existe", "", JOptionPane.PLAIN_MESSAGE);
                } else {
                    anio = Integer.parseInt(txtAnioCapataz.getText());
                    Capataz unCapataz = new Capataz(nombre, cedula, direccion, anio);
                    sistema.agregarCapataz(unCapataz);
                    JOptionPane.showMessageDialog(this, "Capataz registrado correctamente", "", JOptionPane.PLAIN_MESSAGE);
                    //System.out.println(unCapataz);
                }
            }
            objetoAPantalla();

        }

    }//GEN-LAST:event_btnRegistrarCapatazActionPerformed

    private void txtAnioCapatazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioCapatazActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioCapatazActionPerformed

    private void txtDireccionCapatazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionCapatazActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionCapatazActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarCapataz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarCapataz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarCapataz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarCapataz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarCapataz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarCapataz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnioCapataz;
    private javax.swing.JLabel lblCedulaCapataz;
    private javax.swing.JLabel lblDireccionCapataz;
    private javax.swing.JLabel lblNombreCapataz;
    private javax.swing.JTextField txtAnioCapataz;
    private javax.swing.JTextField txtCedulaCapataz;
    private javax.swing.JTextField txtDireccionCapataz;
    private javax.swing.JTextField txtNombreCapataz;
    // End of variables declaration//GEN-END:variables

    private int datosValidos(String nombre, String cedula, String direccion, int anio) {
        int error = 0;
        if (nombre.isEmpty() || cedula.isEmpty() || direccion.isEmpty()) {
            error = 1;
        } else {
            try {
                anio = Integer.parseInt(txtAnioCapataz.getText());
            } catch (NumberFormatException e) {
                error = 2;
            }
        }
        return error;
    }
}
